spring.application.name=SpringBootMVCJSP-100

server.port=8888
server.servlet.context-path=/sai

spring.mvc.view.prefix=/Web-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/springjdbc
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=create