spring.application.name=SpringBootMVCJSPFBPractice
server.port=8085
server.servlet.context-path=/fb

spring.mvc.view.prefix=/Web-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/springjdbc
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true