spring.application.name=SpringBootJSONArrays-8

spring.datasource.url=jdbc:postgresql://localhost:5432/springjdbc
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create